

#ifndef MCU_INTERNAL_H
#define MCU_INTERNAL_H

#include "Std_Types.h"
#include "Mcu_Config.h"
#include "Mcu_InternalTypes.h"



typedef struct {
	/*RCC_CR Register*/
	VAR(RCC_CrHSIType,AUTOMATIC) 		unHSI;
	VAR(RCC_CrHSITRIMType,AUTOMATIC) 	unHSITRIM;
	VAR(RCC_CrHSEType,AUTOMATIC) 		unHSE;
	VAR(RCC_CrHSEBYPType,AUTOMATIC)		unHSEBYP;
	VAR(RCC_CrCSSType,AUTOMATIC) 		unCSS;
	VAR(RCC_CrPLLType,AUTOMATIC) 		unPLL;
	VAR(RCC_CrPLLI2SType,AUTOMATIC) 	unPLLI2S;

	/*RCC_PLLCFGR Register*/
	VAR(RCC_CFgrPLLMType,AUTOMATIC) 	unPLLM;
	VAR(RCC_CFgrPLLNType,AUTOMATIC) 	unPLLN;
	VAR(RCC_CFgrPLLPType,AUTOMATIC) 	unPLLP;
	VAR(RCC_CFgrPLLSRCType,AUTOMATIC)	unPLLSRC;
	VAR(RCC_CFgrPLLQType,AUTOMATIC) 	unPLLQ;

	/*RCC_CFGR Register*/
	VAR(RCC_CfgrSwType,AUTOMATIC)      	unSw;
	VAR(RCC_CfgrHRPEType,AUTOMATIC)     unHRPE;
	VAR(RCC_CfgrPre1_AHBType,AUTOMATIC) unPre1AHB;
	VAR(RCC_CfgrPre2_AHBType,AUTOMATIC) unPre2AHB;
	VAR(RCC_CfgrRTCPREType,AUTOMATIC)   unRTCPRE;
    VAR(RCC_CfgrMCO1Type,AUTOMATIC) 	unMCo1;
    VAR(RCC_CfgrI2SSRCType,AUTOMATIC)   unI2SSRC;
    VAR(RCC_CfgrMCO1PREType,AUTOMATIC)  unMco1Pre;
	VAR(RCC_CfgrMCO2PREType,AUTOMATIC)  unMco2Pre;
	VAR(RCC_CfgrMco2Type,AUTOMATIC)     unMco2;


	/*RCC_CIR Register*/
	VAR(RCC_CIR_LSIRDYIEIType,AUTOMATIC)  unLSIRDYIEI;
	VAR(RCC_CIR_LSERDYIEIType,AUTOMATIC)  unLSERDYIEI;
	VAR(RCC_CIR_HSIRDYIEIType,AUTOMATIC)  unHSIRDYIEI;
	VAR(RCC_CIR_HSERDYIEIType,AUTOMATIC)  unHSERDYIEI;
	VAR(RCC_CIR_PLLRDYIELIType,AUTOMATIC) unPLLRDYIELI;
	VAR(RCC_CIR_PLLI2SRDYIEType,AUTOMATIC)unPLLI2SRDYIE;

	/*RCC_AHB1ENRRegister*/

	VAR(RCC_AHB1GPIOAENType,AUTOMATIC)  	unGPIOA;
	VAR(RCC_AHB1GPIOBENType,AUTOMATIC) 		unGPIOB;
	VAR(RCC_AHB1GPIOCENType,AUTOMATIC) 		unGPIOC;
	VAR(RCC_AHB1GPIODENType,AUTOMATIC) 		unGPIOD;
	VAR(RCC_AHB1GPIOEENType,AUTOMATIC) 		unGPIOE;
	VAR(RCC_AHB1GPIOFENType,AUTOMATIC) 		unGPIOF;
	VAR(RCC_AHB1GPIOGENType,AUTOMATIC) 		unGPIOG;
	VAR(RCC_AHB1GPIOHENType,AUTOMATIC)		unGPIOH;
	VAR(RCC_AHB1GPIOIENType,AUTOMATIC)		unGPIOI;
	VAR(RCC_AHB1CRCENType,AUTOMATIC)   		unCRC;
	VAR(RCC_AHB1BKPSRAMENType,AUTOMATIC)    unKPSRMA;
	VAR(RCC_AHB1CCMDATARAMENType,AUTOMATIC) unCCMDATARAM;
	VAR(RCC_AHB1DMA1ENType,AUTOMATIC)       unDMA1;
	VAR(RCC_AHB1DMA2ENType,AUTOMATIC)		unDMA2;
	VAR(RCC_AHB1ETHMACENType,AUTOMATIC)     unETHMAC;
	VAR(RCC_AHB1ETHMACTXENType,AUTOMATIC) 	unETHMACTX;
	VAR(RCC_AHB1ETHMACRXENType,AUTOMATIC)  	unETHMACRX;
	VAR(RCC_AHB1ETHMACPTPENType,AUTOMATIC)  unETHMACPTP;
	VAR(RCC_AHB1OTGHSENType,AUTOMATIC) 		unOTGHS;
	VAR(RCC_AHB1OTGHSULPIENType,AUTOMATIC)  un1OTGHSULPI;

	/*RCC_AHB2ENRregister*/
	VAR(RCC_AHB2DCMIENType,AUTOMATIC) 		unDCMI;
	VAR(RCC_AHB2CRYPENType,AUTOMATIC)    	unCRYP;
	VAR(RCC_AHB2HASHType,AUTOMATIC)			unHASH;
	VAR(RCC_AHB2RNGENType,AUTOMATIC) 		unRNG;
	VAR(RCC_AHB2OTGFSType,AUTOMATIC) 		unOTGFS;

	/*RCC_AHB3ENRregister*/
	VAR(RCC_AHB3FSMCType,AUTOMATIC) 		unFSMC;

	/*RCC_APB1ENRregister*/
	VAR(RCC_APB1TIM2ENType,AUTOMATIC)       unTIM2;
	VAR(RCC_APB1TIM3ENType,AUTOMATIC) 		unTIM3;
	VAR(RCC_APB1TIM4ENType,AUTOMATIC)		unTIM4;
	VAR(RCC_APB1TIM5ENType,AUTOMATIC)   	unTIM5;
	VAR(RCC_APB1TIM6ENType,AUTOMATIC)  		unTIM6;
	VAR(RCC_APB1TIM7ENType,AUTOMATIC)  		unTIM7;
	VAR(RCC_APB1TIM12ENType,AUTOMATIC) 		unTIM12;
	VAR(RCC_APB1TIM13ENType,AUTOMATIC)		unTIM13;
	VAR(RCC_APB1TIM14ENType,AUTOMATIC) 		unTIM14;
	VAR(RCC_APB1WWDGENType,AUTOMATIC) 		unWWDG;
	VAR(RCC_APB1SPI2ENType,AUTOMATIC) 		unSPI2;
	VAR(RCC_APB1SPI3ENType,AUTOMATIC) 		unSPI3;
	VAR(RCC_APB1USART2ENType,AUTOMATIC) 	unUSART2;
	VAR(RCC_APB1USART3ENType,AUTOMATIC)    	unUSART3;
	VAR(RCC_APB1UART4ENType,AUTOMATIC) 		unUART4;
	VAR(RCC_APB1UART5ENType,AUTOMATIC) 		unUART5;
	VAR(RCC_APB1I2C1ENType,AUTOMATIC) 		unI2C1;
	VAR(RCC_APB1I2C2ENType,AUTOMATIC) 		unI2C2;
	VAR(RCC_APB1I2C3ENType,AUTOMATIC) 		unI2C3;
	VAR(RCC_APB1CAN1ENType,AUTOMATIC) 		unCAN1;
	VAR(RCC_APB1CAN2ENType,AUTOMATIC) 		unCAN2;
	VAR(RCC_APB1PWRENType,AUTOMATIC) 		unPWR;
	VAR(RCC_APB1DACENType,AUTOMATIC) 		unDAC;

	/*RCC_APB2ENRregister*/
	VAR(RCC_APB2TIM1ENType,AUTOMATIC) 		unTIM1;
	VAR(RCC_APB2TIM8ENType,AUTOMATIC) 		unTIM8;
	VAR(RCC_APB2USART1ENType,AUTOMATIC) 	unUSART1;
	VAR(RCC_APB2USART6ENType,AUTOMATIC) 	unUSART6;
	VAR(RCC_APB2ADC3ENType,AUTOMATIC) 		unADC3;
	VAR(RCC_APB2SDIOENType,AUTOMATIC) 		unSDIO;
	VAR(RCC_APB2SPI1ENType,AUTOMATIC) 		unSPI1;
	VAR(RCC_APB2SYSCFGENType,AUTOMATIC) 	unSYSCFG;
	VAR(RCC_APB2TIM9ENType,AUTOMATIC) 		unTIM9;
	VAR(RCC_APB2TIM10ENType,AUTOMATIC) 		unTIM10;
	VAR(RCC_APB2TIM11ENType,AUTOMATIC) 		unTIM11;


	/*RCC_APB2BDCRregister*/
	VAR(RCC_BDCRLSEType,AUTOMATIC) 			unLSE;
	VAR(RCC_BDCRLSEBYPType,AUTOMATIC) 		unLSEBYP;
	VAR(RCC_BDCRRTCSELType,AUTOMATIC) 		unRTCSEL;
	VAR(RCC_BDCRTCENType,AUTOMATIC) 		unTCEN;
	VAR(RCC_BDCRBDType,AUTOMATIC) 			unBD;


	/*RCC_CSRregister*/
	VAR(RCC_CSRLSIType,AUTOMATIC) 			unLSI;

	/*RCC_SSCGRregister*/
	VAR(RCC_SSCGRSPREADSEType,AUTOMATIC) 	unSPREADSEL;
	VAR(RCC_SSCGRSSCGENType,AUTOMATIC) 		unSSCGEN;

	/*RCC_PLLI2SCFGRregister*/
	VAR(RCC_PLLI2SCFGRPLLI2SN0Type,AUTOMATIC) unPLLI2SN0;
	VAR(RCC_PLLI2SCFGRPLLI2SR2Type,AUTOMATIC) unPLLI2SR2;

}McuClockConfigType;

typedef struct{
	VAR(PwrCRLPDSType,AUTOMATIC) 				unLPDS;
	VAR(PwrCRPDDSType,AUTOMATIC) 				unPDDS;
	VAR(PwrCRPVDEType,AUTOMATIC) 				unPVDE;
	VAR(PwrCRPLSType,AUTOMATIC) 				unPLS;
	VAR(PwrCRDBPType,AUTOMATIC) 				unDBP;
	VAR(PwrCRFPDSType,AUTOMATIC) 				uFPDS2;
	VAR(PwrCRVOSType,AUTOMATIC) 				unVOS;


	VAR(PwrCSREWUPType,AUTOMATIC)				unEWUP;
	VAR(PwrCSRBREType,AUTOMATIC) 				unBRE;

}PwrConfigType;

typedef struct{
	VAR(FLASHACRLATENCYType,AUTOMATIC) 			unLATENCY;
	VAR(FLASHACRPRFTENType,AUTOMATIC) 			unPRFTEN;
	VAR(FLASHACRICENType,AUTOMATIC) 			unICEN;
	VAR(FLASHACRDCENType,AUTOMATIC) 			unDCEN;
	VAR(FLASHACRICRSTType,AUTOMATIC) 			unICSR;
	VAR(FLASHACRDCRSTType,AUTOMATIC) 			unDCRS;
}FLASHConfigType;



typedef struct {
	PwrConfigType* PWRConfgSet;
	McuClockConfigType* McuClockConfgSet;
	FLASHConfigType* FlashConfgSet;
}Mcu_ConfigType;



extern McuClockConfigType Mcu_ClockConfigSet[1];
extern PwrConfigType PWR_ConfigSet[1];
extern FLASHConfigType FLASH_ConfigSet[1];
extern Mcu_ConfigType Mcu_ConfigSet[1];

/*RCC Register mask*/

/*RCC_CR Register MAsk*/
#define  RCC_HSI_MASK                 ((uint32)0x00000001)
#define  RCC_HSE_MASK                 ((uint32)0x00010000)
#define  RCC_HSERDY_MASK              ((uint32)0x00020000)
#define  RCC_PLLRDY_MASK              ((uint32)0x02000000)
#define  RCC_HSITRIM_MASK             ((uint32)0x000000F8)
#define  RCC_PLLON_MASK               ((uint32)0x01000000)

/*RCC_AHB1ENR*/
#define  RCC_GPIOA_MASK               ((uint32)0x00000001)
#define  RCC_GPIOB_MASK               ((uint32)0x00000002)
#define  RCC_GPIOC_MASK               ((uint32)0x00000004)
#define  RCC_GPIOD_MASK               ((uint32)0x00000008)
#define  RCC_GPIOH_MASK               ((uint32)0x00000080)
#define  RCC_ETHMAC_MASK              ((uint32)0x02000000)
#define  RCC_ETHMACRX_MASK            ((uint32)0x08000000)
#define  RCC_ETHMACTX_MASK            ((uint32)0x04000000)
#define  RCC_CCMDATARAM_MASK          ((uint32)0x00100000)
#define  RCC_ETHMACPTP_MASK            ((uint32)0x10000000)

/*RCC_APB1ENR*/
#define  RCC_PWREN_MASK               ((uint32)0x10000000)

/*RCC_APB2ENR*/
#define  RCC_SYSCFGEN_MASK               ((uint32)0x00004000)

/*RCC_APB1RSTR MASK */
#define  RCC_TIM2_MASK                ((uint32)0x00000001)
#define  RCC_TIM3_MASK                ((uint32)0x00000002)
#define  RCC_TIM4_MASK                ((uint32)0x00000004)
#define  RCC_TIM5_MASK                ((uint32)0x00000008)
#define  RCC_TIM6_MASK                ((uint32)0x00000010)
#define  RCC_CAN1_MASK                ((uint32)0x02000000)
#define  RCC_CAN2_MASK                ((uint32)0x04000000)

/*RCC_PLLCFGR Register MAsk*/
#define  RCC_PLLCFGR_MASK             ((uint32)0x0F437FFF)
#define  RCC_PLLCFGR_PLLM_MASK        ((uint32)0x0000003F)
#define  RCC_PLLCFGR_PLLN_MASK        ((uint32)0x00007FC0)
#define  RCC_PLLCFGR_PLLP_MASK        ((uint32)0x00030000)
#define  RCC_PLLCFGR_PLLQ_MASK        ((uint32)0x0F000000)
#define  RCC_PLLCFGR_PLLSRC_MASK      ((uint32)0x00400000)

/*RCC_CFGR Register MAsk*/
#define  RCC_HPRE_MASK                ((uint32)0x000000F0)
#define  RCC_PPRE1_MASK               ((uint32)0x00001C00)
#define  RCC_PPRE2_MASK               ((uint32)0x0000E000)
#define  RCC_SW_MASK               ((uint32)0x00000003)


/*PWR Register mask*/
#define  PWR_VOS_MASK                 ((uint32)0x00004000)


/*FLASH Register mask*/
#define  FLASH_LATENCY_MASK          ((uint32)0x00000007)
#define  FLASH_DCEN_MASK             ((uint32)0x00000400)
#define  FLASH_ICEN_MASK             ((uint32)0x00000200)
#define  FLASH_PRFTEN_MASK           ((uint32)0x00000100)

/*AHB1RSTR MASK*/
#define   RCC_AHB1RSTR_MASK            ((uint32)0x226011FF)
#define   RCC_AHB2RSTR_MASK            ((uint32)0x000000F1)
#define   RCC_AHB3RSTR_MASK            ((uint32)0x00000001)
#define   RCC_APB1RSTR_MASK            ((uint32)0x32FEC1FF)
#define   RCC_APB2RSTR_MASK            ((uint32)0x0007593)






#endif /* MCU_INTERNAL_H */
