#ifndef MCU_REGTYPES_H
#define MCU_REGTYPES_H

#include "Std_Types.h"


#define RCCREG_BASE            	(0x40023800UL)
#define FLASHREG_BASE         	(0x40023C00UL)
#define PWRREG_BASE          	(0x40007000UL)





/*RCC_CR Offset Definitions*/

#define  RCC_CR_OFFSET_ADDR32            ((uint32)0x0000UL)

/*RCC_PLLCFGR Offset Definitions*/

#define  RCC_PLLCFGR_OFFSET_ADDR32       ((uint32)0x0004UL)


/*RCC_CFGR Offset Definitions*/

#define  RCC_CFGR_OFFSET_ADDR32          ((uint32)0x0008UL)


/*RCC_CIR Offset Definitions*/

#define  RCC_CIR_OFFSET_ADDR32           ((uint32)0x000CUL)



#define  RCC_AHB1RSTR_OFFSET_ADDR32      ((uint32)0x0010UL)



#define  RCC_AHB2RSTR_OFFSET_ADDR32      ((uint32)0x0014UL)


#define  RCC_AHB3RSTR_OFFSET_ADDR32      ((uint32)0x0018UL)


#define  RCC_APB1RSTR_OFFSET_ADDR32      ((uint32)0x0020UL)


#define  RCC_APB2RSTR_OFFSET_ADDR32      ((uint32)0x0024UL)



#define  RCC_AHB1ENR_OFFSET_ADDR32        ((uint32)0x0030UL)


#define  RCC_AHB2ENR_OFFSET_ADDR32        ((uint32)0x0034UL)

#define  RCC_AHB3ENR_OFFSET_ADDR32        ((uint32)0x0038UL)


#define  RCC_APB1ENR_OFFSET_ADDR32        ((uint32)0x0040UL)


#define  RCC_APB2ENR_OFFSET_ADDR32        ((uint32)0x0044UL)


#define  RCC_AHB1LPENR_OFFSET_ADDR32       ((uint32)0x0050UL)


#define  RCC_AHB2LPENR_OFFSET_ADDR32        ((uint32)0x0054UL)

#define  RCC_AHB3LPENR_OFFSET_ADDR32        ((uint32)0x0058UL)

#define  RCC_APB1LPENR_OFFSET_ADDR32        ((uint32)0x0060UL)

#define  RCC_APB2LPENR_OFFSET_ADDR32        ((uint32)0x0064UL)

#define  RCC_BDCR_OFFSET_ADDR32             ((uint32)0x0070UL)

#define  RCC_CSR_OFFSET_ADDR32              ((uint32)0x0074UL)

#define  RCC_SSCGR_OFFSET_ADDR32            ((uint32)0x0080UL)


#define  RCC_PLLI2SCFGR_OFFSET_ADDR32       ((uint32)0x0084UL)





/*Pwr Registers offset*/
#define  PWR_CR_OFFSET_ADDR32              ((uint32)0x0000UL)

#define  PWR_CSR_OFFSET_ADDR32             ((uint32)0x0004UL)


/*Flash Registers offset*/
#define  FLASH_ACR_OFFSET_ADDR32           ((uint32)0x0000UL)



/*RCC Registers*/


#define RCC_CR_ADDR             (RCCREG_BASE + RCC_CR_OFFSET_ADDR32)
#define RCC_PLLCFGR_ADDR        (RCCREG_BASE + RCC_PLLCFGR_OFFSET_ADDR32)
#define RCC_CFGR_ADDR           (RCCREG_BASE + RCC_CFGR_OFFSET_ADDR32)
#define RCC_CIR_ADDR            (RCCREG_BASE + RCC_CIR_OFFSET_ADDR32)
#define RCC_AHB1RSTR_ADDR       (RCCREG_BASE + RCC_AHB1RSTR_OFFSET_ADDR32)
#define RCC_AHB2RSTR_ADDR       (RCCREG_BASE + RCC_AHB2RSTR_OFFSET_ADDR32)
#define RCC_AHB3RSTR_ADDR       (RCCREG_BASE + RCC_AHB3RSTR_OFFSET_ADDR32)
#define RCC_APB1RSTR_ADDR       (RCCREG_BASE + RCC_APB1RSTR_OFFSET_ADDR32)
#define RCC_APB2RSTR_ADDR       (RCCREG_BASE + RCC_APB2RSTR_OFFSET_ADDR32)
#define RCC_AHB1ENR_ADDR        (RCCREG_BASE + RCC_AHB1ENR_OFFSET_ADDR32)
#define RCC_AHB2ENR_ADDR        (RCCREG_BASE + RCC_AHB2ENR_OFFSET_ADDR32)
#define RCC_AHB3ENR_ADDR        (RCCREG_BASE + RCC_AHB3ENR_OFFSET_ADDR32)
#define RCC_APB1ENR_ADDR        (RCCREG_BASE + RCC_APB1ENR_OFFSET_ADDR32)
#define RCC_APB2ENR_ADDR        (RCCREG_BASE + RCC_APB2ENR_OFFSET_ADDR32)
#define RCC_AHB1LPENR_ADDR      (RCCREG_BASE + RCC_AHB1LPENR_OFFSET_ADDR32)
#define RCC_AHB2LPENR_ADDR      (RCCREG_BASE + RCC_AHB2LPENR_OFFSET_ADDR32)
#define RCC_AHB3LPENR_ADDR      (RCCREG_BASE + RCC_AHB3LPENR_OFFSET_ADDR32)
#define RCC_APB1LPENR_ADDR      (RCCREG_BASE + RCC_APB1LPENR_OFFSET_ADDR32)
#define RCC_APB2LPENR_ADDR      (RCCREG_BASE + RCC_APB2LPENR_OFFSET_ADDR32)
#define RCC_BDCR_ADDR           (RCCREG_BASE + RCC_BDCR_ADDR32)
#define RCC_CSR_ADDR            (RCCREG_BASE + RCC_CSR_OFFSET_ADDR32)
#define RCC_SSCGR_ADDR          (RCCREG_BASE + RCC_SSCGR_OFFSET_ADDR32)
#define RCC_PLLI2SCFGR_ADDR     (RCCREG_BASE + RCC_PLLI2SCFGR_OFFSET_ADDR32)


/*Power Register */
#define PWR_CR_ADDR     (PWRREG_BASE + PWR_CR_OFFSET_ADDR32)

#define PWR_CSR_ADDR    (PWRREG_BASE + PWR_CSR_OFFSET_ADDR32)


/*Flash Register*/
#define FLASH_ACR_ADDR    (FLASHREG_BASE + FLASH_ACR_OFFSET_ADDR32)


#endif /* MCU_REGTYPES_H */
