/*
 * Gpt_Cfg.c
 *
 *  Created on: Jul 31, 2024
 *      Author: AshsihP
 */

#include "Std_Types.h"
#include "Gpt_Cfg.h"
#include "Platform_Types.h"
void TIM2_IRQ_Handler(void);
void TIM5_IRQ_Handler(void);

static const Gpt_ConfigType Gpt_TimConfigDefault[]=
{/*TimerIDType*//*unTimAvblValue*//*Cr1UdisType*//*Cr1URSType*//*Cr1OpmType*//*Cr1DirType*//*Cr1CMSType*//*Cr1ArrType*//*Cr1CkdType*//*ARRValue*//*CNTValue*//*PscValue*/

		{ TIM_1,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_2,    TRUE,   UEV_ENABLED,  UDIS_DISABLED, OPM_DISABLED, UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x09 },
		{ TIM_3,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_4,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_5,    TRUE,   UEV_ENABLED,  UDIS_DISABLED, OPM_DISABLED, UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x09 },
		{ TIM_6,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_7,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_8,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_9,    FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_10,   FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_11,   FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_12,   FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_13,   FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 },
		{ TIM_14,   FALSE,  UEV_ENABLED,  UDIS_ENABLED,  OPM_ENABLED,  UPCOUNTER,   Edge_ALIGNMODE ,ARR_DISABLED, SAMPLING_CLOCK, 0xFFFFFFFF , 0x00000000, 0x53 }
};




CONST(GPT_TimerConfigType, GPT_CONST) Gpt_Config[1] =
{
		{
				14,        /*no. of Timer*/

				Gpt_TimConfigDefault  /*Timer Configuration*/
		}
};


void TIM2_IRQ_Handler()
{   // Check if update interrupt flag is set)
	if ((REG_READ32(TIMx_SR_ADDR(TIM_2)) & GPT_SR_UIF_MASK) != 0)
	{
		REG_RMW32(TIMx_SR_ADDR(TIM_2), GPT_SR_UIF_MASK, UIF_CLEARED);
	}
}

void TIM5_IRQ_Handler()
{
	// Check if update interrupt flag is set)
	if ((REG_READ32(TIMx_SR_ADDR(TIM_5)) & GPT_SR_UIF_MASK) != 0)
	{
		REG_RMW32(TIMx_SR_ADDR(TIM_5), GPT_SR_UIF_MASK, UIF_CLEARED);

	}
}




