# SVN-Id: $Id: intcfg.mk 52032 2017-01-17 13:19:54Z ostwal01 $
# SVN-Url: $HeadURL: http://debesvn001/kostal/lk_ae_internal/LK/Eclipse/ProjectTemplate/trunk/Tools/Make/intcfg.mk $

######################################################################
#
# MAKEFILE TEMPLATE AEP2
#
# See /doc for detailed documentation
#
# Internal configuration options of the make process. This file should
# not be modified by a user.
######################################################################


######################################################################
# Version information
######################################################################

# Toolchain release version for the make process.
BuildProcessVersion = 2017-MS1



######################################################################
# Standard directories
######################################################################

# Root directory of the project
BaseDir = ../..

# Directory containing QA-C related build process files.
QacPrj = ${BaseDir}/Tools/Qac

# Directory containing Tessy related build process files.
TessyPrj = ${BaseDir}/Tools/Tessy

# Directory containing generated file lists.
SrcListDir = ./lists

# Direcory containing generated source dependency information. 
DependencyDir = ./dep


######################################################################
# User configuration files
######################################################################

# Directory containing all make process configuration files
MK_CONFIG_DIR = config

# list of make process config files
MK_CONFIG_FILES = project.mk compile_opt.mk assemble_opt.mk \
    link_opt.mk blacklist.mk qac_opt.mk qac_blacklist.mk tessy_opt.mk


######################################################################
# Misc configuration options
######################################################################

# Extension of object files generated by the compiler 
C_OBJ_EXT = .o

# Extension of object files generated by the assembler
ASM_OBJ_EXT = .o

# Extension of generated dependecy files
DEP_EXT = .d

