#include "Std_Types.h"
#include "Port_Cfg.h"
#include "Platform_Types.h"
static const Port_Port_Ci_PinConfigType Port_aPinConfigDefault[]=
{
		/*Pin*/ /*PinAvbl*/ /*GpioID*/	/*MODER*/ 				/*OTYPER*/ 					/*OSPEEDR*/ 		       /*PUPDR*/ 				/*LCKR*/					/*AFRL*/ 		/*AFRH*/
/* 0*/		{ 0,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection, 	AF0_Selection },
/* 1*/		{ 1,   FALSE,	 GPIO_A,	    PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED, AF0_Selection,	AF0_Selection },
/* 2*/		{ 2,   FALSE,	 GPIO_A,	    PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED, AF0_Selection,	AF0_Selection },
/* 3*/		{ 3,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,  NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 4*/		{ 4,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 5*/		{ 5,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 6*/		{ 6,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 7*/		{ 7,   FALSE,	 GPIO_A,	    PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 8*/		{ 8,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 9*/		{ 9,   FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 10*/		{ 10,  FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 11*/		{ 11,  FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 12*/		{ 12,  FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 13*/		{ 13,  FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 14*/		{ 14,  FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 15*/		{ 15,  FALSE,	 GPIO_A,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },

/* 16*/		{ 0,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 17*/		{ 1,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 18*/		{ 2,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 19*/		{ 3,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 20*/		{ 4,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 21*/		{ 5,   FALSE,	 GPIO_B,        PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 22*/		{ 6,   FALSE,	 GPIO_B,        PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,       PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 23*/		{ 7,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 24*/		{ 8,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 25*/		{ 9,   FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 26*/		{ 10,  FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 27*/		{ 11,  FALSE,	 GPIO_B,	    PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 28*/		{ 12,  FALSE,	 GPIO_B,	    PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 29*/		{ 13,  FALSE,	 GPIO_B,	    PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 30*/		{ 14,  FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 31*/		{ 15,  FALSE,	 GPIO_B,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },

/* 32*/		{ 0,   TRUE,	 GPIO_C,		PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 33*/		{ 1,   TRUE,	 GPIO_C,	    PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 34*/		{ 2,   TRUE,	 GPIO_C,		PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 35*/		{ 3,   TRUE,	 GPIO_C,		PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 36*/		{ 4,   TRUE,	 GPIO_C,	    PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 37*/		{ 5,   TRUE,	 GPIO_C,	    PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 38*/		{ 6,   TRUE,	 GPIO_C,		PORT_PIN_MODE_OUTPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 39*/		{ 7,   FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 40*/		{ 8,   FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 41*/		{ 9,   FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 42*/		{ 10,  FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 43*/		{ 11,  FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 44*/		{ 12,  FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 45*/		{ 13,  FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 46*/		{ 14,  FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 47*/		{ 15,  FALSE,	 GPIO_C,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },

/* 48*/		{ 0,   TRUE,	 GPIO_D,		PORT_PIN_MODE_ALTERNATE_FUNCTION,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_VERY_HIGH,	PULLUP,		                PORT_PIN_CFG_NOT_LOCKED,	AF9_Selection,	AF0_Selection },
/* 49*/		{ 1,   TRUE,	 GPIO_D,		PORT_PIN_MODE_ALTERNATE_FUNCTION,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_VERY_HIGH,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF9_Selection,	AF0_Selection },
/* 50*/		{ 2,   FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 51*/		{ 3,   FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 52*/		{ 4,   FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 53*/		{ 5,   TRUE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			PULLUPDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 54*/		{ 6,   TRUE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			PULLUPDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 55*/		{ 7,   FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 56*/		{ 8,   FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 57*/		{ 9,   FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 58*/		{ 10,  FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 59*/		{ 11,  FALSE,	 GPIO_D,		PORT_PIN_MODE_INPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 60*/		{ 12,  TRUE,	 GPIO_D,		PORT_PIN_MODE_OUTPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 61*/		{ 13,  TRUE,	 GPIO_D,		PORT_PIN_MODE_OUTPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 62*/		{ 14,  TRUE,	 GPIO_D,		PORT_PIN_MODE_OUTPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 63*/		{ 15,  TRUE,	 GPIO_D,		PORT_PIN_MODE_OUTPUT,				PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,			NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },

/* 64*/		{ 0,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 65*/		{ 1,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 66*/		{ 2,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 67*/		{ 3,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 68*/		{ 4,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 69*/		{ 5,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 70*/		{ 6,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 71*/		{ 7,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 72*/		{ 8,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 73*/		{ 9,   FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 74*/		{ 10,  FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 75*/		{ 11,  FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 76*/		{ 12,  FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 77*/		{ 13,  FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 78*/		{ 14,  FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
/* 79*/		{ 15,  FALSE,	 GPIO_E,		PORT_PIN_MODE_INPUT,	PORT_PIN_OTYPE_PUSH_PULL, GPIO_SPEED_FREQ_LOW,	NO_PULLUP_NOPULLDOWN,		PORT_PIN_CFG_NOT_LOCKED,	AF0_Selection,	AF0_Selection },
};


CONST(Port_ConfigType, PORT_CONST) Port_Config[1] =
{
		{
				80,

				Port_aPinConfigDefault
		}
};

